name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false 

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Build Production Versions
        run: |
          sudo apt-get update
          sudo apt-get install rsync -y
          sudo apt-get install xsltproc -y
          rsync dev/index.xml build/
          rsync dev/index.xsl build/
          rsync dev/diagram.xml build/
          rsync dev/diagrams.xsl build/
          rsync dev/symbols.svg build/
          rsync --recursive dev/exposes build/
          rsync --recursive dev/includes build/
          rsync --recursive dev/assets build/
          npm install clean-css-cli uglify-js -g
          cat dev/assets/js/* | uglifyjs -o build/assets/js/main.min.js
          cleancss -o build/assets/css/main.min.css dev/assets/css/build.css
          cleancss -o build/assets/css/theme.min.css dev/assets/css/theme/build.css
          cleancss -o build/assets/css/utilities.min.css dev/assets/css/utilities/build.css
          cleancss -o build/assets/css/patterns.min.css dev/assets/css/patterns/build.css
          xsltproc dev/index.xml > build/index.full.html
          xsltproc dev/goods.xml > build/goods.html
          find build/exposes -name index.xml | awk '{system("xsltproc " $1 " > $(dirname " $1 ")/index.html")}'
          xsltproc dev/diagrams.xsl dev/index.xml > build/diagrams.html
          xsltproc dev/minified.xsl dev/index.xml > build/index.min.html
          xsltproc dev/progressive.xsl dev/index.xml > build/index.html
          sed '/xsl:include/d' dev/index.xsl > build/index-complete.xsl ; sed '/xsl:stylesheet/d;/\?xml/d' dev/includes/* | sed -i '$e cat /dev/stdin' build/index-complete.xsl
          cp dev/index.xml build/index-complete.xml
          sed -i 's/index\.xsl/index-complete\.xsl/' build/index-complete.xml

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build
          keep_files: true
